"""Résolution des noms d'équipes entre sources. Un nom inconnu lève TeamAliasError, jamais deviné."""
import unicodedata

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.team import Team, TeamAlias

SOURCES = ("fd_uk", "fd_org", "odds_api")


class TeamAliasError(LookupError):
    def __init__(self, source: str, alias: str):
        super().__init__(f"nom d'équipe inconnu pour {source}: {alias!r}")
        self.source, self.alias = source, alias


def normalize(name: str) -> str:
    """minuscules, sans accents, espaces réduits — clé de comparaison des alias."""
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    return " ".join(s.lower().split())


# (nom canonique, pays, {source: [alias, ...]}) — le nom canonique est lui-même un alias implicite pour chaque source.
KNOWN_TEAMS: list[tuple[str, str, dict[str, list[str]]]] = [
    # ---- Angleterre (Premier League 2025/26)
    ("Arsenal", "Angleterre", {"fd_org": ["Arsenal FC"]}),
    ("Aston Villa", "Angleterre", {"fd_org": ["Aston Villa FC"]}),
    ("Bournemouth", "Angleterre", {"fd_org": ["AFC Bournemouth"]}),
    ("Brentford", "Angleterre", {"fd_org": ["Brentford FC"]}),
    ("Brighton", "Angleterre", {"fd_org": ["Brighton & Hove Albion FC"], "odds_api": ["Brighton and Hove Albion"]}),
    ("Burnley", "Angleterre", {"fd_org": ["Burnley FC"]}),
    ("Chelsea", "Angleterre", {"fd_org": ["Chelsea FC"]}),
    ("Crystal Palace", "Angleterre", {"fd_org": ["Crystal Palace FC"]}),
    ("Everton", "Angleterre", {"fd_org": ["Everton FC"]}),
    ("Fulham", "Angleterre", {"fd_org": ["Fulham FC"]}),
    ("Leeds", "Angleterre", {"fd_org": ["Leeds United FC"], "odds_api": ["Leeds United"]}),
    ("Liverpool", "Angleterre", {"fd_org": ["Liverpool FC"]}),
    ("Manchester City", "Angleterre", {"fd_uk": ["Man City"], "fd_org": ["Manchester City FC"]}),
    ("Manchester United", "Angleterre", {"fd_uk": ["Man United"], "fd_org": ["Manchester United FC"]}),
    ("Newcastle", "Angleterre", {"fd_org": ["Newcastle United FC"], "odds_api": ["Newcastle United"]}),
    ("Nottingham Forest", "Angleterre", {"fd_uk": ["Nott'm Forest"], "fd_org": ["Nottingham Forest FC"]}),
    ("Sunderland", "Angleterre", {"fd_org": ["Sunderland AFC"]}),
    ("Tottenham", "Angleterre", {"fd_org": ["Tottenham Hotspur FC"], "odds_api": ["Tottenham Hotspur"]}),
    ("West Ham", "Angleterre", {"fd_org": ["West Ham United FC"], "odds_api": ["West Ham United"]}),
    ("Wolves", "Angleterre", {"fd_org": ["Wolverhampton Wanderers FC"], "odds_api": ["Wolverhampton Wanderers"]}),
    # ---- France (Ligue 1 2025/26)
    ("Angers", "France", {"fd_org": ["Angers SCO"]}),
    ("Auxerre", "France", {"fd_org": ["AJ Auxerre"]}),
    ("Brest", "France", {"fd_org": ["Stade Brestois 29"], "odds_api": ["Stade Brestois 29"]}),
    ("Le Havre", "France", {"fd_org": ["Le Havre AC"]}),
    ("Lens", "France", {'fd_org': ['RC Lens', 'Racing Club de Lens'], 'odds_api': ['RC Lens']}),
    ("Lille", "France", {"fd_org": ["Lille OSC"]}),
    ("Lorient", "France", {"fd_org": ["FC Lorient"]}),
    ("Lyon", "France", {"fd_org": ["Olympique Lyonnais"], "odds_api": ["Olympique Lyonnais"]}),
    ("Marseille", "France", {"fd_org": ["Olympique de Marseille"], "odds_api": ["Marseille", "Olympique Marseille"]}),
    ("Metz", "France", {"fd_org": ["FC Metz"]}),
    ("Monaco", "France", {"fd_org": ["AS Monaco FC"], "odds_api": ["AS Monaco"]}),
    ("Nantes", "France", {"fd_org": ["FC Nantes"]}),
    ("Nice", "France", {"fd_org": ["OGC Nice"]}),
    ("Paris FC", "France", {"fd_org": ["Paris FC"]}),
    ("Paris Saint-Germain", "France", {"fd_uk": ["Paris SG"], "fd_org": ["Paris Saint-Germain FC"], "odds_api": ["Paris Saint Germain", "Paris Saint-Germain"]}),
    ("Rennes", "France", {"fd_org": ["Stade Rennais FC 1901"], "odds_api": ["Stade Rennais"]}),
    ("Strasbourg", "France", {"fd_org": ["RC Strasbourg Alsace"]}),
    ("Toulouse", "France", {"fd_org": ["Toulouse FC"]}),
    # ---- Espagne (La Liga 2025/26)
    ("Alavés", "Espagne", {"fd_uk": ["Alaves"], "fd_org": ["Deportivo Alavés"], "odds_api": ["Alaves", "Deportivo Alaves"]}),
    ("Athletic Bilbao", "Espagne", {"fd_uk": ["Ath Bilbao"], "fd_org": ["Athletic Club"], "odds_api": ["Athletic Club", "Athletic Bilbao"]}),
    ("Atlético Madrid", "Espagne", {"fd_uk": ["Ath Madrid"], "fd_org": ["Club Atlético de Madrid"], "odds_api": ["Atletico Madrid", "Atlético Madrid"]}),
    ("Barcelona", "Espagne", {"fd_org": ["FC Barcelona"]}),
    ("Celta Vigo", "Espagne", {"fd_uk": ["Celta"], "fd_org": ["RC Celta de Vigo"]}),
    ("Elche", "Espagne", {'fd_org': ['Elche CF'], 'odds_api': ['Elche CF']}),
    ("Espanyol", "Espagne", {"fd_uk": ["Espanol"], "fd_org": ["RCD Espanyol de Barcelona"]}),
    ("Getafe", "Espagne", {"fd_org": ["Getafe CF"]}),
    ("Girona", "Espagne", {"fd_org": ["Girona FC"]}),
    ("Levante", "Espagne", {"fd_org": ["Levante UD"]}),
    ("Mallorca", "Espagne", {"fd_org": ["RCD Mallorca"]}),
    ("Osasuna", "Espagne", {'fd_org': ['CA Osasuna'], 'odds_api': ['CA Osasuna']}),
    ("Real Oviedo", "Espagne", {"fd_uk": ["Oviedo"], "fd_org": ["Real Oviedo"], "odds_api": ["Oviedo"]}),
    ("Rayo Vallecano", "Espagne", {"fd_uk": ["Vallecano"], "fd_org": ["Rayo Vallecano de Madrid"]}),
    ("Real Betis", "Espagne", {"fd_uk": ["Betis"], "fd_org": ["Real Betis Balompié"]}),
    ("Real Madrid", "Espagne", {"fd_org": ["Real Madrid CF"]}),
    ("Real Sociedad", "Espagne", {"fd_uk": ["Sociedad"], "fd_org": ["Real Sociedad de Fútbol"]}),
    ("Sevilla", "Espagne", {"fd_org": ["Sevilla FC"]}),
    ("Valencia", "Espagne", {"fd_org": ["Valencia CF"]}),
    ("Villarreal", "Espagne", {"fd_org": ["Villarreal CF"]}),
    # ---- Allemagne (Bundesliga 2025/26)
    ("Augsburg", "Allemagne", {"fd_org": ["FC Augsburg"], "odds_api": ["FC Augsburg"]}),
    ("Bayer Leverkusen", "Allemagne", {"fd_uk": ["Leverkusen"], "fd_org": ["Bayer 04 Leverkusen"]}),
    ("Bayern Munich", "Allemagne", {"fd_org": ["FC Bayern München"], "odds_api": ["Bayern München", "FC Bayern Munich"]}),
    ("Borussia Dortmund", "Allemagne", {"fd_uk": ["Dortmund"], "fd_org": ["Borussia Dortmund"]}),
    ("Borussia Mönchengladbach", "Allemagne", {"fd_uk": ["M'gladbach"], "fd_org": ["Borussia Mönchengladbach"], "odds_api": ["Borussia Monchengladbach"]}),
    ("Eintracht Frankfurt", "Allemagne", {"fd_uk": ["Ein Frankfurt"], "fd_org": ["Eintracht Frankfurt"]}),
    ("Freiburg", "Allemagne", {"fd_org": ["SC Freiburg"], "odds_api": ["SC Freiburg"]}),
    ("Hamburg", "Allemagne", {"fd_org": ["Hamburger SV"], "odds_api": ["Hamburger SV"]}),
    ("Heidenheim", "Allemagne", {"fd_org": ["1. FC Heidenheim 1846"], "odds_api": ["1. FC Heidenheim"]}),
    ("Hoffenheim", "Allemagne", {"fd_org": ["TSG 1899 Hoffenheim"], "odds_api": ["TSG Hoffenheim"]}),
    ("Köln", "Allemagne", {"fd_uk": ["FC Koln"], "fd_org": ["1. FC Köln"], "odds_api": ["FC Cologne", "1. FC Köln"]}),
    ("Mainz", "Allemagne", {'fd_org': ['1. FSV Mainz 05'], 'odds_api': ['1. FSV Mainz 05', 'FSV Mainz 05']}),
    ("RB Leipzig", "Allemagne", {"fd_org": ["RB Leipzig"]}),
    ("St. Pauli", "Allemagne", {"fd_uk": ["St Pauli"], "fd_org": ["FC St. Pauli 1910"], "odds_api": ["FC St. Pauli"]}),
    ("Stuttgart", "Allemagne", {"fd_org": ["VfB Stuttgart"], "odds_api": ["VfB Stuttgart"]}),
    ("Union Berlin", "Allemagne", {"fd_org": ["1. FC Union Berlin"]}),
    ("Werder Bremen", "Allemagne", {"fd_org": ["SV Werder Bremen"]}),
    ("Wolfsburg", "Allemagne", {"fd_org": ["VfL Wolfsburg"], "odds_api": ["VfL Wolfsburg"]}),
    # ---- Italie (Serie A 2025/26)
    ("Atalanta", "Italie", {'fd_org': ['Atalanta BC'], 'odds_api': ['Atalanta BC']}),
    ("Bologna", "Italie", {"fd_org": ["Bologna FC 1909"]}),
    ("Cagliari", "Italie", {"fd_org": ["Cagliari Calcio"]}),
    ("Como", "Italie", {"fd_org": ["Como 1907"]}),
    ("Cremonese", "Italie", {"fd_org": ["US Cremonese"]}),
    ("Fiorentina", "Italie", {"fd_org": ["ACF Fiorentina"]}),
    ("Genoa", "Italie", {"fd_org": ["Genoa CFC"]}),
    ("Inter", "Italie", {"fd_org": ["FC Internazionale Milano"], "odds_api": ["Inter Milan"]}),
    ("Juventus", "Italie", {"fd_org": ["Juventus FC"]}),
    ("Lazio", "Italie", {"fd_org": ["SS Lazio"]}),
    ("Lecce", "Italie", {"fd_org": ["US Lecce"]}),
    ("Milan", "Italie", {"fd_org": ["AC Milan"], "odds_api": ["AC Milan"]}),
    ("Napoli", "Italie", {"fd_org": ["SSC Napoli"]}),
    ("Parma", "Italie", {"fd_org": ["Parma Calcio 1913"]}),
    ("Pisa", "Italie", {"fd_org": ["Pisa SC"]}),
    ("Roma", "Italie", {"fd_org": ["AS Roma"], "odds_api": ["AS Roma"]}),
    ("Sassuolo", "Italie", {"fd_org": ["US Sassuolo Calcio"]}),
    ("Torino", "Italie", {"fd_org": ["Torino FC"]}),
    ("Udinese", "Italie", {"fd_org": ["Udinese Calcio"]}),
    ("Verona", "Italie", {"fd_org": ["Hellas Verona FC"], "odds_api": ["Hellas Verona"]}),
    # ---- relégués 2024/25 présents dans l'historique fd_uk (utile à la forme et aux face-à-face)
    ("Leicester", "Angleterre", {"fd_org": ["Leicester City FC"], "odds_api": ["Leicester City"]}),
    ("Ipswich", "Angleterre", {"fd_org": ["Ipswich Town FC"], "odds_api": ["Ipswich Town"]}),
    # ---- promus 2026/27 dans les cinq championnats domestiques (orthographes observées dans fixtures.csv)
    ("Schalke 04", "Allemagne", {'fd_org': ['FC Schalke 04'], 'odds_api': ['FC Schalke 04']}),
    ("SC Paderborn 07", "Allemagne", {'fd_uk': ['Paderborn'], 'odds_api': ['SC Paderborn']}),
    ("SV Elversberg", "Allemagne", {'fd_uk': ['Elversberg'], 'fd_org': ['SV 07 Elversberg'], 'odds_api': ['Elversberg']}),
    ("Hull City", "Angleterre", {"fd_uk": ["Hull"], "fd_org": ["Hull City AFC"]}),
    ("Coventry City", "Angleterre", {"fd_uk": ["Coventry"], "fd_org": ["Coventry City FC"]}),
    ("ESTAC Troyes", "France", {'fd_uk': ['Troyes'], 'odds_api': ['Troyes'], 'fd_org': ['ES Troyes AC']}),
    ("Le Mans FC", "France", {"fd_uk": ["Le Mans"], "odds_api": ["Le Mans"]}),
    ("Venezia FC", "Italie", {"fd_uk": ["Venezia"], "odds_api": ["Venezia"]}),
    ("Frosinone Calcio", "Italie", {"fd_uk": ["Frosinone"], "odds_api": ["Frosinone"]}),
    ("AC Monza", "Italie", {"fd_uk": ["Monza"], "odds_api": ["Monza"]}),
    ("Racing Santander", "Espagne", {'fd_uk': ['Santander'], 'fd_org': ['Real Racing Club de Santander'], 'odds_api': ['Real Racing Club de Santander']}),
    ("Málaga CF", "Espagne", {"fd_uk": ["Malaga"], "odds_api": ["Malaga"]}),
    ("Deportivo La Corogne", "Espagne", {'fd_uk': ['La Coruna'], 'odds_api': ['Deportivo La Coruña', 'Deportivo La Coruna'], 'fd_org': ['RC Deportivo de La Coruña', 'RC Deportivo La Coruña']}),
    # ---- Ligue des Champions 2026/27, clubs hors des cinq championnats domestiques (pas de calendrier fd_uk)
    ("PSV Eindhoven", "Pays-Bas", {"fd_org": ["PSV"]}),
    ("Feyenoord", "Pays-Bas", {"fd_org": ["Feyenoord Rotterdam"]}),
    ("NEC Nijmegen", "Pays-Bas", {"fd_uk": ['Nijmegen'], "fd_org": ["NEC"]}),
    ("Porto", "Portugal", {"fd_org": ["FC Porto"], "odds_api": ["FC Porto"]}),
    ("Sporting CP", "Portugal", {"fd_uk": ['Sp Lisbon'], "fd_org": ["Sporting Clube de Portugal"], "odds_api": ["Sporting Lisbon"]}),
    ("Club Brugge", "Belgique", {"fd_org": ["Club Brugge KV"]}),
    ("Union Saint-Gilloise", "Belgique", {"fd_uk": ['St. Gilloise'], "fd_org": ["Royale Union Saint-Gilloise"], "odds_api": ["Union Saint Gilloise", "Union St. Gilloise"]}),
    ("Slavia Prague", "Tchéquie", {"fd_org": ["SK Slavia Praha"], "odds_api": ["Slavia Praha"]}),
    ("Galatasaray", "Turquie", {"fd_org": ["Galatasaray SK"]}),
    ("Shakhtar Donetsk", "Ukraine", {'fd_org': ['FC Shakhtar Donetsk', 'FK Shakhtar Donetsk']}),
    ("Viking", "Norvège", {"fd_org": ["Viking FK"], "odds_api": ["Viking FK"]}),
    ("AEK Athens", "Grèce", {'fd_org': ['AEK Athens FC', 'PAE AEK']}),
    ("LASK", "Autriche", {"fd_org": ["LASK Linz"], "odds_api": ["LASK Linz"]}),
    ("Celtic", "Écosse", {"fd_org": ["Celtic FC"]}),
    # ---- Ligue Europa 2026/27, clubs hors des cinq championnats domestiques (liste partielle, à compléter via
    # l'outil quarantine quand des orthographes inconnues apparaissent)
    ("AZ Alkmaar", "Pays-Bas", {"fd_org": ["AZ"]}),
    ("Torreense", "Portugal", {"fd_org": ["CD Torreense"]}),
    ("Hapoel Be'er Sheva", "Israël", {"fd_org": ["Hapoel Be'er Sheva FC"], "odds_api": ["Hapoel Beer Sheva"]}),
    ("Dinamo Zagreb", "Croatie", {"fd_org": ["GNK Dinamo Zagreb"]}),
    ("Celje", "Slovénie", {'fd_org': ['NK Celje'], 'odds_api': ['NK Celje']}),
    ("Levski Sofia", "Bulgarie", {'fd_org': ['PFC Levski Sofia'], 'odds_api': ['PFC Levski Sofia']}),
    ("Sparta Prague", "Tchéquie", {"fd_org": ["AC Sparta Praha"], "odds_api": ["Sparta Praha"]}),
    ("Olympiacos", "Grèce", {'fd_org': ['Olympiacos FC'], 'odds_api': ['Olympiakos', 'Olympiakos Piraeus']}),
    ("Sturm Graz", "Autriche", {'fd_org': ['SK Sturm Graz'], 'odds_api': ['SK Sturm Graz']}),
    # ---- Coupes d'Europe 2026/27, clubs vus dans les calendriers/cotes réels du 11/09/2026
    ("Slovan Bratislava", "Slovaquie", {"fd_org": ["ŠK Slovan Bratislava"], "odds_api": ["ŠK Slovan Bratislava"]}),
    ("Fenerbahçe", "Turquie", {"fd_org": ["Fenerbahçe SK"], "odds_api": ["Fenerbahce"]}),
    ("Bodø/Glimt", "Norvège", {"fd_org": ["FK Bodø/Glimt"], "odds_api": ["Bodo/Glimt"]}),
    ("Sabah FK", "Azerbaïdjan", {}),
    ("Omonoia Nicosie", "Chypre", {"odds_api": ["Omonoia FC"]}),
    ("Ararat-Armenia", "Arménie", {"odds_api": ["FC Ararat-Armenia"]}),
    ("Benfica", "Portugal", {"fd_org": ["SL Benfica", "Sport Lisboa e Benfica"]}),
    ("Anderlecht", "Belgique", {"fd_org": ["RSC Anderlecht"]}),
    ("OFI Crète", "Grèce", {"odds_api": ["OFI Crete"]}),
    ("RB Salzburg", "Autriche", {"odds_api": ["Salzburg"], "fd_org": ["FC Red Bull Salzburg"]}),
    ("Beşiktaş", "Turquie", {"odds_api": ["Besiktas JK"], "fd_org": ["Beşiktaş JK"]}),
    ("Ferencváros", "Hongrie", {"odds_api": ["Ferencváros TC"]}),
    ("Lech Poznań", "Pologne", {}),
    ("Lillestrøm", "Norvège", {"odds_api": ["Lillestrom"]}),
    ("Viktoria Plzeň", "Tchéquie", {"odds_api": ["Viktoria Plzen"], "fd_org": ["FC Viktoria Plzeň"]}),
    ("Jagiellonia Białystok", "Pologne", {}),

    # ---- Angleterre (Championship 2026/27, mode gratuit fd_uk)
    ('Birmingham', 'Angleterre', {'fd_org': ['Birmingham City FC']}),
    ('Blackburn', 'Angleterre', {'fd_org': ['Blackburn Rovers FC']}),
    ('Bolton', 'Angleterre', {'fd_org': ['Bolton Wanderers FC']}),
    ('Bristol City', 'Angleterre', {'fd_org': ['Bristol City FC']}),
    ('Cardiff', 'Angleterre', {'fd_org': ['Cardiff City FC']}),
    ('Charlton', 'Angleterre', {'fd_org': ['Charlton Athletic FC']}),
    ('Derby', 'Angleterre', {'fd_org': ['Derby County FC']}),
    ('Lincoln', 'Angleterre', {'fd_org': ['Lincoln City FC']}),
    ('Middlesbrough', 'Angleterre', {'fd_org': ['Middlesbrough FC']}),
    ('Millwall', 'Angleterre', {'fd_org': ['Millwall FC']}),
    ('Norwich', 'Angleterre', {'fd_org': ['Norwich City FC']}),
    ('Portsmouth', 'Angleterre', {'fd_org': ['Portsmouth FC']}),
    ('Preston', 'Angleterre', {'fd_org': ['Preston North End FC']}),
    ('QPR', 'Angleterre', {'fd_org': ['Queens Park Rangers FC']}),
    ('Sheffield United', 'Angleterre', {'fd_org': ['Sheffield United FC']}),
    ('Southampton', 'Angleterre', {'fd_org': ['Southampton FC']}),
    ('Stoke', 'Angleterre', {'fd_org': ['Stoke City FC']}),
    ('Swansea', 'Angleterre', {'fd_org': ['Swansea City AFC']}),
    ('Watford', 'Angleterre', {'fd_org': ['Watford FC']}),
    ('West Brom', 'Angleterre', {'fd_org': ['West Bromwich Albion FC']}),
    ('Wrexham', 'Angleterre', {'fd_org': ['Wrexham AFC']}),
    # ---- Allemagne (2. Bundesliga 2026/27, mode gratuit fd_uk)
    ('Bielefeld', 'Allemagne', {}),
    ('Bochum', 'Allemagne', {}),
    ('Braunschweig', 'Allemagne', {}),
    ('Cottbus', 'Allemagne', {}),
    ('Darmstadt', 'Allemagne', {}),
    ('Dresden', 'Allemagne', {}),
    ('Greuther Furth', 'Allemagne', {}),
    ('Hannover', 'Allemagne', {}),
    ('Hertha', 'Allemagne', {}),
    ('Holstein Kiel', 'Allemagne', {}),
    ('Kaiserslautern', 'Allemagne', {}),
    ('Karlsruhe', 'Allemagne', {}),
    ('Magdeburg', 'Allemagne', {}),
    ('Nurnberg', 'Allemagne', {}),
    ('Osnabruck', 'Allemagne', {}),
    # ---- Italie (Serie B 2026/27, mode gratuit fd_uk)
    ('Arezzo', 'Italie', {}),
    ('Ascoli', 'Italie', {}),
    ('Avellino', 'Italie', {}),
    ('Benevento', 'Italie', {}),
    ('Carrarese', 'Italie', {}),
    ('Catanzaro', 'Italie', {}),
    ('Cesena', 'Italie', {}),
    ('Empoli', 'Italie', {}),
    ('Juve Stabia', 'Italie', {}),
    ('Mantova', 'Italie', {}),
    ('Modena', 'Italie', {}),
    ('Padova', 'Italie', {}),
    ('Palermo', 'Italie', {}),
    ('Sampdoria', 'Italie', {}),
    ('Sudtirol', 'Italie', {}),
    ('Vicenza', 'Italie', {}),
    ('Virtus Entella', 'Italie', {}),
    # ---- Espagne (Liga 2 2026/27, mode gratuit fd_uk)
    ('Albacete', 'Espagne', {}),
    ('Almeria', 'Espagne', {}),
    # « Andorra » seul désigne la sélection chez The Odds API : le club garde ce nom pour fd_uk uniquement.
    ('FC Andorra', 'Espagne', {'fd_uk': ['Andorra']}),
    ('Burgos', 'Espagne', {}),
    ('Cadiz', 'Espagne', {}),
    ('Castellon', 'Espagne', {}),
    ('Celta B', 'Espagne', {}),
    ('Ceuta', 'Espagne', {}),
    ('Cordoba', 'Espagne', {}),
    ('Eibar', 'Espagne', {}),
    ('Eldense', 'Espagne', {}),
    ('Granada', 'Espagne', {}),
    ('Las Palmas', 'Espagne', {}),
    ('Leganes', 'Espagne', {}),
    ('Sabadell', 'Espagne', {}),
    ('Sociedad B', 'Espagne', {}),
    ('Sp Gijon', 'Espagne', {}),
    ('Tenerife', 'Espagne', {}),
    ('Valladolid', 'Espagne', {}),
    # ---- France (Ligue 2 2026/27, mode gratuit fd_uk)
    ('Annecy', 'France', {}),
    ('Boulogne', 'France', {}),
    ('Clermont', 'France', {}),
    ('Dijon', 'France', {}),
    ('Dunkerque', 'France', {}),
    ('Grenoble', 'France', {}),
    ('Guingamp', 'France', {}),
    ('Laval', 'France', {}),
    ('Montpellier', 'France', {}),
    ('Nancy', 'France', {}),
    ('Pau FC', 'France', {}),
    ('Red Star', 'France', {}),
    ('Reims', 'France', {}),
    ('Rodez', 'France', {}),
    ('Sochaux', 'France', {}),
    ('St Etienne', 'France', {}),
    # ---- Pays-Bas (Eredivisie 2026/27, mode gratuit fd_uk)
    ('Ajax', 'Pays-Bas', {'fd_org': ['AFC Ajax']}),
    ('Cambuur', 'Pays-Bas', {'fd_org': ['SC Cambuur-Leeuwarden']}),
    ('Den Haag', 'Pays-Bas', {'fd_org': ['ADO Den Haag']}),
    ('Excelsior', 'Pays-Bas', {'fd_org': ['SBV Excelsior']}),
    ('For Sittard', 'Pays-Bas', {'fd_org': ['Fortuna Sittard']}),
    ('Go Ahead Eagles', 'Pays-Bas', {}),
    ('Groningen', 'Pays-Bas', {'fd_org': ['FC Groningen']}),
    ('Heerenveen', 'Pays-Bas', {'fd_org': ['SC Heerenveen']}),
    ('Sparta Rotterdam', 'Pays-Bas', {}),
    ('Telstar', 'Pays-Bas', {'fd_org': ['Telstar 1963']}),
    ('Twente', 'Pays-Bas', {'fd_org': ["FC Twente '65"]}),
    ('Utrecht', 'Pays-Bas', {'fd_org': ['FC Utrecht']}),
    ('Willem II', 'Pays-Bas', {'fd_org': ['Willem II Tilburg']}),
    ('Zwolle', 'Pays-Bas', {'fd_org': ['PEC Zwolle']}),
    # ---- Portugal (Liga Portugal 2026/27, mode gratuit fd_uk)
    ('Academico Viseu', 'Portugal', {'fd_org': ['Académico de Viseu FC']}),
    ('Alverca', 'Portugal', {'fd_org': ['FC Alverca']}),
    ('Arouca', 'Portugal', {'fd_org': ['FC Arouca']}),
    ('Casa Pia', 'Portugal', {'fd_org': ['Casa Pia AC']}),
    ('Estoril', 'Portugal', {'fd_org': ['GD Estoril Praia']}),
    ('Estrela', 'Portugal', {'fd_org': ['CF Estrela da Amadora']}),
    ('Famalicao', 'Portugal', {'fd_org': ['FC Famalicão']}),
    ('Gil Vicente', 'Portugal', {'fd_org': ['Gil Vicente FC']}),
    ('Guimaraes', 'Portugal', {'fd_org': ['Vitória SC']}),
    ('Maritimo', 'Portugal', {'fd_org': ['CS Marítimo']}),
    ('Moreirense', 'Portugal', {'fd_org': ['Moreirense FC']}),
    ('Nacional', 'Portugal', {'fd_org': ['CD Nacional']}),
    ('Rio Ave', 'Portugal', {'fd_org': ['Rio Ave FC']}),
    ('Santa Clara', 'Portugal', {'fd_org': ['CD Santa Clara']}),
    ('Sp Braga', 'Portugal', {'fd_org': ['Sporting Clube de Braga']}),
    # ---- Belgique (Pro League 2026/27, mode gratuit fd_uk)
    ('Antwerp', 'Belgique', {}),
    ('Beveren', 'Belgique', {}),
    ('Cercle Brugge', 'Belgique', {}),
    ('Charleroi', 'Belgique', {}),
    ('Genk', 'Belgique', {}),
    ('Gent', 'Belgique', {}),
    ('Kortrijk', 'Belgique', {}),
    ('Lommel SK', 'Belgique', {}),
    ('Mechelen', 'Belgique', {}),
    ('Oud-Heverlee Leuven', 'Belgique', {}),
    ('RAAL La Louviere', 'Belgique', {}),
    ('St Truiden', 'Belgique', {}),
    ('Standard', 'Belgique', {}),
    ('Waregem', 'Belgique', {}),
    ('Westerlo', 'Belgique', {}),
    # ---- Turquie (Süper Lig 2026/27, mode gratuit fd_uk)
    ('Alanyaspor', 'Turquie', {}),
    ('Amedspor', 'Turquie', {}),
    ('Buyuksehyr', 'Turquie', {}),
    ('Corum', 'Turquie', {}),
    ('Erzurumspor', 'Turquie', {}),
    ('Eyupspor', 'Turquie', {}),
    ('Gaziantep', 'Turquie', {}),
    ('Genclerbirligi', 'Turquie', {}),
    ('Goztep', 'Turquie', {}),
    ('Kasimpasa', 'Turquie', {}),
    ('Kocaelispor', 'Turquie', {}),
    ('Konyaspor', 'Turquie', {}),
    ('Rizespor', 'Turquie', {}),
    ('Samsunspor', 'Turquie', {}),
    ('Trabzonspor', 'Turquie', {}),
    # ---- Grèce (Super League 2026/27, mode gratuit fd_uk)
    ('AEK', 'Grèce', {}),
    ('Aris', 'Grèce', {}),
    ('Asteras Tripolis', 'Grèce', {}),
    ('Atromitos', 'Grèce', {}),
    ('Iraklis', 'Grèce', {}),
    ('Kalamata', 'Grèce', {}),
    ('Kifisia', 'Grèce', {}),
    ('Levadeiakos', 'Grèce', {}),
    ('PAOK', 'Grèce', {}),
    ('Panathinaikos', 'Grèce', {}),
    ('Panetolikos', 'Grèce', {}),
    ('Volos NFC', 'Grèce', {}),
    # ---- Écosse (Premiership 2026/27, mode gratuit fd_uk)
    ('Aberdeen', 'Écosse', {}),
    ('Dundee', 'Écosse', {}),
    ('Dundee United', 'Écosse', {}),
    ('Falkirk', 'Écosse', {}),
    ('Hearts', 'Écosse', {}),
    ('Hibernian', 'Écosse', {}),
    ('Kilmarnock', 'Écosse', {}),
    ('Motherwell', 'Écosse', {}),
    ('Rangers', 'Écosse', {}),
    ('St Johnstone', 'Écosse', {}),
    ('St Mirren', 'Écosse', {}),
    # ---- Sélections nationales (Ligue des Nations 2026/27). Alias odds_api = noms anglais du relevé du 22/09/2026.
    ('Andorre', 'Sélections', {'odds_api': ['Andorra']}),
    ('Arménie', 'Sélections', {'odds_api': ['Armenia']}),
    ('Autriche', 'Sélections', {'odds_api': ['Austria']}),
    ('Azerbaïdjan', 'Sélections', {'odds_api': ['Azerbaijan']}),
    ('Belgique', 'Sélections', {'odds_api': ['Belgium']}),
    ('Bosnie-Herzégovine', 'Sélections', {'odds_api': ['Bosnia & Herzegovina']}),
    ('Bulgarie', 'Sélections', {'odds_api': ['Bulgaria']}),
    ('Croatie', 'Sélections', {'odds_api': ['Croatia']}),
    ('Chypre', 'Sélections', {'odds_api': ['Cyprus']}),
    ('Tchéquie', 'Sélections', {'odds_api': ['Czech Republic']}),
    ('Danemark', 'Sélections', {'odds_api': ['Denmark']}),
    ('Angleterre', 'Sélections', {'odds_api': ['England']}),
    ('Estonie', 'Sélections', {'odds_api': ['Estonia']}),
    ('Îles Féroé', 'Sélections', {'odds_api': ['Faroe Islands']}),
    ('Finlande', 'Sélections', {'odds_api': ['Finland']}),
    ('France', 'Sélections', {}),
    ('Géorgie', 'Sélections', {'odds_api': ['Georgia']}),
    ('Allemagne', 'Sélections', {'odds_api': ['Germany']}),
    ('Gibraltar', 'Sélections', {}),
    ('Grèce', 'Sélections', {'odds_api': ['Greece']}),
    ('Hongrie', 'Sélections', {'odds_api': ['Hungary']}),
    ('Islande', 'Sélections', {'odds_api': ['Iceland']}),
    ('Israël', 'Sélections', {}),
    ('Italie', 'Sélections', {'odds_api': ['Italy']}),
    ('Kazakhstan', 'Sélections', {}),
    ('Kosovo', 'Sélections', {}),
    ('Lettonie', 'Sélections', {'odds_api': ['Latvia']}),
    ('Liechtenstein', 'Sélections', {}),
    ('Lituanie', 'Sélections', {'odds_api': ['Lithuania']}),
    ('Luxembourg', 'Sélections', {}),
    ('Malte', 'Sélections', {'odds_api': ['Malta']}),
    ('Moldavie', 'Sélections', {'odds_api': ['Moldova']}),
    ('Monténégro', 'Sélections', {}),
    ('Pays-Bas', 'Sélections', {'odds_api': ['Netherlands']}),
    ('Macédoine du Nord', 'Sélections', {'odds_api': ['North Macedonia']}),
    ('Irlande du Nord', 'Sélections', {'odds_api': ['Northern Ireland']}),
    ('Norvège', 'Sélections', {'odds_api': ['Norway']}),
    ('Pologne', 'Sélections', {'odds_api': ['Poland']}),
    ('Portugal', 'Sélections', {}),
    ('Irlande', 'Sélections', {'odds_api': ['Republic of Ireland']}),
    ('Roumanie', 'Sélections', {'odds_api': ['Romania']}),
    ('Saint-Marin', 'Sélections', {'odds_api': ['San Marino']}),
    ('Écosse', 'Sélections', {'odds_api': ['Scotland']}),
    ('Serbie', 'Sélections', {'odds_api': ['Serbia']}),
    ('Slovaquie', 'Sélections', {'odds_api': ['Slovakia']}),
    ('Slovénie', 'Sélections', {'odds_api': ['Slovenia']}),
    ('Espagne', 'Sélections', {'odds_api': ['Spain']}),
    ('Suède', 'Sélections', {'odds_api': ['Sweden']}),
    ('Suisse', 'Sélections', {'odds_api': ['Switzerland']}),
    ('Turquie', 'Sélections', {'odds_api': ['Turkey']}),
    ('Ukraine', 'Sélections', {}),
    ('Pays de Galles', 'Sélections', {'odds_api': ['Wales']}),
]


def seed_aliases(db: Session) -> int:
    """Crée les équipes et leurs alias manquants. Idempotent. Retourne le nombre d'alias créés."""
    created = 0
    existing_teams = {t.name: t for t in db.scalars(select(Team)).all()}
    existing_aliases = {(a.source, normalize(a.alias)) for a in db.scalars(select(TeamAlias)).all()}
    for name, country, per_source in KNOWN_TEAMS:
        team = existing_teams.get(name)
        if team is None:
            team = Team(name=name, country=country)
            db.add(team); db.flush()
            existing_teams[name] = team
        for source in SOURCES:
            for alias in [name, *per_source.get(source, [])]:
                key = (source, normalize(alias))
                if key in existing_aliases:
                    continue
                db.add(TeamAlias(source=source, alias=normalize(alias), team_id=team.id))
                existing_aliases.add(key); created += 1
    db.commit()
    return created


def resolve_team(db: Session, source: str, alias: str) -> Team:
    if source not in SOURCES:
        raise ValueError(f"source inconnue : {source}")
    key = normalize(alias)
    row = db.scalar(select(TeamAlias).where(TeamAlias.source == source, TeamAlias.alias == key))
    if row is None:
        # Repli : le même nom connu pour une autre source (ex. « CA Osasuna » écrit par fd_org et par odds_api).
        # On l'accepte seulement s'il désigne une seule équipe, et on mémorise l'alias pour cette source.
        others = db.scalars(select(TeamAlias).where(TeamAlias.alias == key)).all()
        teams = {a.team_id: a.team for a in others}
        if len(teams) != 1:
            raise TeamAliasError(source, alias)
        row = TeamAlias(source=source, alias=key, team_id=next(iter(teams)))
        db.add(row); db.flush()
    return row.team
